### ISSUE TITLE
Documentation and testing

### ISSUE THREAD

**Issue by smorad** [facebookresearch/salina#26]
This is a really interesting framework, I'd love to move some of our code to it. The workspace abstraction should greatly simplify our multiagent and recurrent models. I am a bit worried about the readability/correctness though -- are there any plans to write up proper documentation (e.g. https://readthedocs.org) and unit tests?

**Comment by ludc** [comment]
Good point. Right now, we have more invested on the development side than on the doc and test side (even if we have some tests internally to check the implementation). And yes, I think it is definitively a good framework for multi-agent and recurrent models. 

Writing a better documentation is a wokr in progress, we expect to have one in the next two weeks, focused on the salina package (the salina_examples will right now stay with few documentation since we think that the code is almost enough to understand the examples if one knows how salina works). I will close this issue once detailed documentation is available

**Comment by ludc** [comment]
In the meantime, feel free to reach me (e.g by messenger) if you have any question, I will be happy to help.

**Comment by ludc** [comment]
The 'main' piece of code is the Workspace code. I will write the documentation ASAP. If workspace is documented, then everything becomes simple to check and understand (since an Agent is basically anything that writes/reads in a workspace)

**Comment by ludc** [comment]
A documentation has been started in the 'documentation' branch. Use `mkdocs serve` from the salina directory to visualize the documentation. When finished, it will be deployed on `readthedocs`

**Comment by ludc** [comment]
Hi, documentation is available at: https://salina.readthedocs.io/en/latest/
