### ISSUE TITLE
Do you have any plan to be the flexible size for workspace?

### ISSUE THREAD

**Issue by aithlab** [facebookresearch/salina#46]
Hi, 

I've recently been using your library for a reinforcement learning project.
More precisely, I'm interested in multi-agent systems that provide multiple rewards for them.
In my environment, after the one-step, it provides n_agents x 1 size of rewards.
However, in the workspace, it initializes the reward as "torch.tensor([0.0]).float()" at the first time step(t=0).
So, at the second time step, it could not set the new reward whose size is "n_agents x 1" because the occupied reward size is torch.Size([1]).
I may think there are many cases that have multiple dimensions of reward not only in my environment but also in other environments.

I carefully think it could be more useful if your library supports a flexible reward size.

Best regards,

**Comment by ludc** [comment]
Hi, 

 The workspace automatically adapt to the size of the variables that are written in it. Said otherwise, you can perfectly have an 'environment agent' that writes multiple reward functions, or reward with multiple dimensions> Right now, the gym wrapper only writes a reward of size 1 because it corresponds to the openAI gym specifications, but you can redefine this wrapper to computes multiple rewards.

One you cannot do is to have a reward with a time varying size (e.g not the same size at each timestep).

 Does it help ?

 Regards,

 Ludovic

**Comment by aithlab** [comment]
Thanks for the reply!

My environment inherits GymAgent from salina.agents.gyma. 
Do you mean that GymAgent has a fixed reward size of 1, so it could be difficult to resize?
The code raises "AssertionError: Incompatible size" because the reward size is set to 1 in '_reset' method in GymAgent.
And if I want to adjust the reward size, do you mean that GymAgent should be redefined?

Regards,
